### ISSUE TITLE
Error in Environment Setup 

### ISSUE THREAD

**Issue by seo-0** [DKU-StarLab/leveldb-study#10]
![스크린샷(649)](https://user-images.githubusercontent.com/95268620/179799755-4746af9b-9e1b-452a-bc41-f6449288d5cc.png)

안녕하세요, 늦은시간 issue사항 업데이트 관하여 양해의 말씀 먼저 구하겠습니다, 죄송합니다.

다름이 아니라 오른쪽 사진의 터미널 창 아래에서 네번째 줄부터 이제 environment setup을 설정하기 위해 sudo su, swapoff --all까지 실행하였는데, 세번째 사항인 echo ~ 부분을 입력한 결과, 다음과 같이

"bash: /proc/sys/vm/zone_reclaim_mode: Read-only file system" 

이라고 오류가 발생하는 것 같습니다. 어떤 부분이 문제가 되었는지 답변 주시면 감사하겠습니다:)

**Comment by min-guk** [comment]
해당 명령어는 zone reclaim이 발생하지 않도록 시스템 설정을 수정하는 것 입니다.
아마 서버에서 학생들에게 시스템 설정 파일의 권한을 read-only로 부여하여, 수정이 불가한 것 같습니다.

사실 intel에서 제공하는 rocksdb db_bench 실험 설정 안내서에 따른 것인데, 굳이 설정하지 않으셔도 괜찮습니다.
- https://www.intel.com/content/dam/develop/external/us/en/documents/rocksdb-benchmark-tuning-guide-on-xeon.pdf

**Comment by seo-0** [comment]
감사합니다:)!!
