### ISSUE TITLE
VSCode 사용법: - solid cloud users

### ISSUE THREAD

**Issue by seehwan** [DKU-StarLab/leveldb-study#13]
VSCode 사용자들에게~
파일과 Remote ssh 연결이 불편했지요? 아래와 같이 하면 됩니다.
Remote-SSH 설정 파일을 다음과 같이 수정하면 됩니다.
(.ssh/config파일 입니다)

아래와 같이 ProxyJump를 쓰면 됩니다.
접속은 solid로 하면 됩니다.

Host solid-proxy
  HostName assam.dankook.ac.kr
  User <자기 solid 계정>
  
Host solid
  HostName 172.20.41.181
  User solid
  Port <자기 port 번호, 아래쪽 번호 참조>
  ProxyJump solid-proxy

--- --- --- 사용자별 port 번호 --- --- ---
며칠 후에 아래 내용은 지울 예정입니다.
seehwan-solid 20002
minguk17 20003
subin21 20005
jayoung26 20006
seoyoung27 20007
sanghyun17 20008
isukim16 20009
seyeon22 20010
sangwoo41 20011
hansu27 20014
pji-solid 20012
seungwon24 20015
seoyoung99 20017

**Comment by seehwan** [comment]
확인하고 난 후에 지울 예정!

**Comment by min-guk** [comment]
친절하게 안내해주셔서 감사합니다! 학생들에게 큰 도움이 될 것 같습니다 ㅎㅎ

**Comment by aarom416** [comment]
안녕하세요 갑자기 vscode에서 solid 접속이 되지 않아 댓글 남깁니다 서버에 접속할때 제가 바꾼 비밀번호를 누르면 바로 들어가졌는데 solid 비밀번호를 누르라고 다시 뜹니다.. 혹시 이유를 알 수 있을까 하여 남깁니다!!

**Comment by min-guk** [comment]
서버 계정 관련한 사항은 스터디원이면서도 유시환 교수님 연구실의 학부연구생인 조태규 학생이 관리해주시는데요. 

조태규 학생 한번 확인해주시고 답변 달아주시면 감사하겠습니다.

Taegyu Cho, wh2446@dankook.ac.kr
