### ISSUE TITLE
shell script 사용법 질문

### ISSUE THREAD

**Issue by sss654654** [DKU-StarLab/leveldb-study#25]
안녕하세요 benchmark 실험 이후 다른 여러 실험을 한번에 수행하여 결과를 보기 위하여 shell scrpit를 사용하려 하였으나
사용방법을 모르겠어서 질문드립니다!

week2 shell script 사용 예
<img width="830" alt="image" src="https://user-images.githubusercontent.com/84978165/181421561-cd28f3cd-8c50-4b21-a1c3-d36a86407db5.png">

week3 shell script 사용 예
<img width="788" alt="image" src="https://user-images.githubusercontent.com/84978165/181421612-7357ac19-f774-4b1f-8af1-734a1dbfeed1.png">

shell script 사용법에 대해서 모르겠는 부분을 짚어 질문을 드리고자 했으나 실행방법에 대해서 감이 잡히지 않아 질문을 특정드려서 하지 못하는 점 양해 부탁드립니다.

혹시 다른 학우분들 중에 shell script로 실험을 한번에 하신 분이 있으시다면 shell script를 사용하는 과정을 알려주시면 감사할 것 같습니다..

**Comment by min-guk** [comment]
위 shell script들은 예시이고, 학생분들이 수정해서 사용하시면 됩니다.

이전에 제가 설명을 너무 간단히 하고 넘어간 것 같아서 db_bench shell script는 주석을 상세히 달아서 업데이트를 했으니 참고하시길 바랍니다. (https://github.com/DKU-StarLab/leveldb-study/issues/24)

uftrace shell script도 주석을 달아서 추후에 다시 안내하도록 하겠습니다.

**Comment by min-guk** [comment]
shell script 문법이나 사용법까지 스터디에서는 다루기에는 양이 많아서, 다루지 못했습니다. shell script가 낯설어서 그렇지 절대 어렵지 않기 때문에, 인터넷에서 검색하면서 공부하시면 쉽게 수정해서 사용 가능하실 것 같습니다. 

아래 강의들과 문서 확인하시길 바라겠습니다.
- [2020 개정판] 이것이 리눅스다(CentOS 8)07장-01교시 셸스크립트-셸 스크립트 개요, 작성법, 실행법, 변수 (https://youtu.be/Z2RxGi_hQA8)
- [따배셸] 1. Linux Shell이란? (+ Shell 구성 실습) (https://youtu.be/dsUyFss2Sh4)
- [Linux] 쉘 스크립트(Shell script) 기초 (https://engineer-mole.tistory.com/200)
- [Shell Script] 간단한 쉘 스크립트 문법 정리와 예제 (https://twpower.github.io/131-simple-shell-script-syntax)

**Comment by min-guk** [comment]
마지막으로 학생 분들 중에서, 쉘 스크립트로 실험을 돌리신 분들이 있다면 pull request로 소스코드 공유해주시고 댓글로 과정을 공유해주시면 감사하겠습니다.

**Comment by sss654654** [comment]
자세한 답변 감사드립니다! 올려주신 자료와 더불어 개인적으로 공부하여 실행시킨 뒤 성공 시켰다면 깃 이슈나 조교님이 말씀해주신 것처럼 소스코드 공유 후 댓글로 과정을 적겠습니다!!

**Comment by arashio1111** [comment]
아래 pull request를 통해서 제가 실험에 사용한 코드와 사용법을 올렸으니 참고해주세요.

https://github.com/DKU-StarLab/leveldb-study/pull/26
