### ISSUE TITLE
Team Selection

### ISSUE THREAD

**Issue by min-guk** [DKU-StarLab/leveldb-study#3]
How's it going?

You will be divided into groups next week.
Each team will study one of the six internal topics as listed below:

1. WAL/Manifest
2. Memtable
3. Compaction
4. SSTable
5. Bloom Filter
6. Cache

Submit your preferred topics in sorted order, starting with your most preferred topic.
Aside from your preferences, other factors will be considered in making the team to balance the teams with the available topics.

Please, write a comment until **7/13 11:00 AM**.
If you don't leave a comment, it will be assumed that you don't have any preferences.

See you next week!

**Comment by min-guk** [comment]
Sample Preference :

Minguk Choi.

1. SSTable
2. WAL/Manifest
3. Bloom Filter
4. Memtable
5. Cache
6. Compaction

**Comment by JongKI-PARK** [comment]
Jongki Park,

1. sstable
2. compaction
3. memtable
4. bloom filter
5. cache
6. WAL/manifest

**Comment by Student5421** [comment]
Suhwan Sin

    1. compaction
    2. memtable
    3. sstable
    4. WAL/manifest
    5. cache
    6. bloom filter

**Comment by SayOny** [comment]
Seyeon Park

1. SSTable
2. WAL/Manifest
3. Cache
4. Compaction
5. Bloom Filter
6. Memtable

**Comment by arashio1111** [comment]
1. memtable
2. compaction
3. SSTable
4. WAL
5. Cache
6. bloom filter

**Comment by ErosBryant** [comment]
1.memtable
2. compaction
3. SSTable
4. WAL/Manifes
5. Cache
6. bloom filter

**Comment by aarom416** [comment]
Sangwoo Kang.
1. compaction
2. memtable
3. SSTable
4. WAL/Manifes
5. bloom filter
6. Cache

**Comment by gillyongs** [comment]
Hansu Kim.

1.Bloom filter
2.Compaction
3.Memtable
4.SSTable
5.WAL/Manifies
6.Cache

**Comment by sss654654** [comment]
Subin Hong.

1.Cache
2.Compaction
3.Memtable
4.SSTable
5.WAL/Manifest
6.Bloom Filter

**Comment by seoyoung927** [comment]
Seoyoung Cho.

1.Bloom filter
2.Compaction
3.SSTable
4.Memtable
5.WAL/Manifies
6.Cache

**Comment by min-guk** [comment]
As I told before, preference submission deadline is extended until **next Wednesday, 7/20 11:00 AM.**

You can edit your preference comment before the deadline.

**Comment by ha-seungwon** [comment]
Seungwon Ha

1.Cache
2.Compaction
3.Memtable
4.WAL/Manifies
5.SSTable
6.Bloom filter

**Comment by HASHTAG-YOU** [comment]
Taegyu Cho

1. Memtable
2. Compaction
3. Cache
4. SSTable
5. Bloom filter
6. WAL/Manifies

**Comment by seo-0** [comment]
Seoyoung Park
1. Cache
2. Compaction
3. Memtable
4. SSTable
5. Bloom filter
6. WAL/Manifies

**Comment by Cho-SangHyun** [comment]
Sanghyun Cho

1. SSTable
2. MemTable
3. Compaction
4. Cache
5. Bloom filter
6. WAL/Manifest

**Comment by cho-ja-young** [comment]
Jayoung Cho

1. SSTable
2. Compaction
3. Memtable
4. Bloom filter
5. Cache
6. WAL/Manifies

**Comment by isu-kim** [comment]
Isu Kim
1. SSTable
2. WAL/Manifest
3. Compaction
4. Memtable
5. Cache
6. Bloom flter

**Comment by min-guk** [comment]
1.WAL/Manifest: [Isu Kim](https://github.com/gooday2die), [Seyeon Park ](https://github.com/SayOny), [Suhwan Shin](https://github.com/Student5421)
2.Memtable: [Taegyu Cho ](https://github.com/HASHTAG-YOU), [Zhu Yongjie](https://github.com/arashio1111)
3.Compaction: [Sangwoo Kang](https://github.com/aarom416), [Seoyoung Park](https://github.com/seo-0), [Zhao Guangxun](https://github.com/ErosBryant)
4.SSTable: [Ja-young Cho](https://github.com/cho-ja-young), [Jongki Park](https://github.com/JongKI-PARK), [Sanghyun Cho](https://github.com/Cho-SangHyun)
5.Bloom Filter: [Hansu Kim](https://github.com/gillyongs), [Seoyoung Cho](https://github.com/ChoSeoyoung)
6.Cache: [Seungwon Ha](https://github.com/ha-seungwon), [Subin Hong](https://github.com/sss654654)

**Comment by min-guk** [comment]
Join Slack and meet your teammates!
- https://join.slack.com/t/dkuleveldbstudy/shared_invite/zt-1cljbqa1f-i9XItb06rpvndmHPp4vwkg
