### ISSUE TITLE
leveldb-wiki-kor feedback (KOR)

### ISSUE THREAD

**Issue by min-guk** [DKU-StarLab/leveldb-study#66]
**[YCSB Contest]**
**- 모든 팀 leveldb-wiki-kor에도 업로드 부탁드립니다.**
2. Memtable 팀 리포트 작성해서 업로드 해주세요.

**[Benchmark Report]**
1. WAL
- 3개의 실험을 각각 다른 마크다운 파일로 분리하는 것이 좋을 것 같습니다.

2. Memtable
- 실험 결과를 표가 아닌 그래프로 나타내는 것이 직관적 일 것 같습니다.
- 실험 결과 표의 값이 latency임을 명시적으로 보여주면 좋을 것 같습니다.
- 맞춤법이 틀린 것이 많은데, 맞춤법을 확인하여 수정하길 바랍니다.

4. SSTable
- 선형 그래프 보다는 막대 그래프가 더 적합한 것 같습니다.

5. BloomFilter
- 선형 그래프 보다는 막대 그래프가 더 적합한 것 같습니다.
- 맨 마지막 표가 어떤 데이터들을 보여주고 싶었고, 어떤 이야기를 하고 싶었는 지에 대한 설명이 부족해보입니다.
따라서 일반적인 표의 형식으로 구성하고, 각 행과 열의 헤더를 표시하는 것이 좋아보입니다.

**[Analysis]**
4. Compaction
- Compaction이 어떤 연산이고, 왜 필요한지, 어떻게 작동하는지 설명이 필요해보입니다.

5. BloomFilter
- 제목을 #을 통해서 글자크기를 조절하여, 확실하게 구분하면 좋을 것 같습니다.
- 그림을 캡쳐하여 첨부하다보니, 화질이 좋지 않은 것 같습니다.
- 코드를 캡쳐하다보니, 화질이 좋지 않은 것 같습니다.  코드블럭을 사용하는 것이 좋을 것 같습니다.
- 벤치마크 내용은 파일을 분리하여, 따로 작성하는 것이 좋아보입니다.

**Comment by min-guk** [comment]
이번에 전자책을 업로드 하면서, WAL팀의 벤치마크 분석글을 지우고 3개로 나누어 다시 업로드 하였습니다.
그런데 다시 생각해보니, 컨트리뷰터가 저로 되어버렸네요. 풀리퀘스트로 각 학생분들께서 삭제하시고 다시 업로드 해주시면 감사하겠습니다.

**Comment by min-guk** [comment]
튜닝 컨테스트 글 또한 제가 일괄적으로 업로드하면서, 모든 글이 제가 작성한 글로 되었습니다.

자신이 컨트리뷰터로 업로드하고 싶으신 분들은, 삭제하시고 다시 업로드 해주시면 감사하겠습니다.

**Comment by min-guk** [comment]
SSTable팀의 그동안 공부한 내용을 상당히 잘 정리하여 업로드하였습니다. 다른 팀 분들도 참고하여, 분석글 작성해주시면 좋을 것 같습니다.

**Comment by min-guk** [comment]
6일 화요일까지 올려주시는 풀리퀘스트는 7일 수요일에 피드백 드리도록 하겠습니다.

**Comment by isu-kim** [comment]
@korea-choi 
> 이번에 전자책을 업로드 하면서, WAL팀의 벤치마크 분석글을 지우고 3개로 나누어 다시 업로드 하였습니다.
그런데 다시 생각해보니, 컨트리뷰터가 저로 되어버렸네요. 풀리퀘스트로 각 학생분들께서 삭제하시고 다시 업로드 해주시면 감사하겠습니다.

해당 내용에 있어서는 컨트리뷰터가 최민국 조교님이 되어도 상관 없을 것 같습니다. 

+ 이후 정리한 내용도 곧 업로드 하도록 하겠습니다
감사합니다

**Comment by min-guk** [comment]
> @korea-choi
> 
> > 이번에 전자책을 업로드 하면서, WAL팀의 벤치마크 분석글을 지우고 3개로 나누어 다시 업로드 하였습니다.
> > 그런데 다시 생각해보니, 컨트리뷰터가 저로 되어버렸네요. 풀리퀘스트로 각 학생분들께서 삭제하시고 다시 업로드 해주시면 감사하겠습니다.
> 
> 해당 내용에 있어서는 컨트리뷰터가 최민국 조교님이 되어도 상관 없을 것 같습니다.
> 
> * 이후 정리한 내용도 곧 업로드 하도록 하겠습니다
>   감사합니다

네, 알겠습니다.

**Comment by min-guk** [comment]
오늘까지 leveldb-wiki에 올려주신 문서들에 대해 풀 리퀘스트 댓글로 피드백 드렸습니다. 다들 개강하여 바쁘신 와중에도, 신경써서 열심히 작성해주셔서 감사합니다. 다들 내용적인 부분 보다는 형식적인 부분을 수정해주시면 될 것 같습니다. 

마지막으로 아직 분석 문서를 업로드 해주시지 않은 팀들은 빠르게 업로드 부탁드리도록 하겠습니다. 얼마 남지 않았으니, 끝까지 잘 정리하여 다 같이 좋은 전자책 만들었으면 좋겠습니다. 감사합니다.

**Comment by min-guk** [comment]
@Cho-SangHyun @JongKI-PARK 
SSTable팀은 제가 풀리퀘스트를 닫아버려서, 이 곳에 추가적인 피드백을 남김니다. 분석 문서의 코드 주석을 기존 LevelDB 주석과 구분할 수 있도록 하여, 영어로 작성해주시길 바라겠습니다. 

감사합니다.

**Comment by min-guk** [comment]
현재 SSTable, Bloom Filter, Cache 팀은 analysis 문서가 마무리가 되었습니다. 고생하셨습니다!

Bloom Filter팀은 브랜치 충돌만 해결해서 다시 풀 리퀘스트만 날려주시면, 머지하도록 하겠습니다.

Compaction팀은 Minor Compaction문서만 피드백 반영해주시면 마무리 될 것 같습니다.

WAL, Memtable 팀은 아직 빠진 부분이 많아, 조원별로 발표내용 정리해서 업로드 해주시면 감사하겠습니다.

**Comment by min-guk** [comment]
현재 memtable 팀을 제외하고 leveldb-wiki 작성이 마무리 되었습니다. 다음주 중으로 memtable 팀까지 마무리되면, 전자책에도 업데이트 하고 공지드리겠습니다.

감사합니다.
