### ISSUE TITLE
LevelDB install, Debug Mode 환경설정 질문

### ISSUE THREAD

**Issue by sss654654** [DKU-StarLab/leveldb-study#8]
2주차 강의 pdf의 43/71페이지 부분의 Debug Mode 환경설정을 따라하던 도중 에러가 발생하였습니다.

[강의 부분]
<img width="348" alt="image" src="https://user-images.githubusercontent.com/84978165/179381988-12eaf4b1-edbf-4135-adc0-517f3291e411.png">

[에러 부분]
<img width="639" alt="image" src="https://user-images.githubusercontent.com/84978165/179381995-646a61fd-be0c-4c55-8cfe-3108a6227512.png">

<img width="445" alt="image" src="https://user-images.githubusercontent.com/84978165/179382026-58d796b8-239e-4f32-a3e4-ff04a686117e.png">

<img width="674" alt="image" src="https://user-images.githubusercontent.com/84978165/179382029-73a1025e-c7ea-49f9-ae8d-716db51cf9d8.png">

CMakeLists.txt에서 추가한 명령어인
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} –g –pg") 이 부분을 지울 경우 빌드가 잘됩니다. 

leveldb에 대한 전반적인 지식이 부족하다보니 구글링을 통해서도 에러를 찾아내기 힘들어 혼자 해내기 힘들다 판단되어 에러사항을 올리게 되었습니다.

문제되는 부분을 찾아주시면 감사할 것 같습니다.

**Comment by min-guk** [comment]
HAVE_GNU_POSIX_REGEX하고 -g -pg옵션 문제는 뭔가 gcc에서 문제가 있는 것 같아요. 한번 최신 버전으로 업데이트 해볼래요?

그리고 혹시 맥북이신가요?

**Comment by sss654654** [comment]
> HAVE_GNU_POSIX_REGEX하고 -g -pg옵션 문제는 뭔가 gcc에서 문제가 있는 것 같아요. 한번 최신 버전으로 업데이트 해볼래요?
> 
> 그리고 혹시 맥북이신가요?

윈도우사용중입니다! gcc -v를 통해 확인한 결과 9.4.0 버전을 사용하고 있는데 11버전으로 업데이트 해보시란 말씀이 맞을까요?

**Comment by min-guk** [comment]
> > HAVE_GNU_POSIX_REGEX하고 -g -pg옵션 문제는 뭔가 gcc에서 문제가 있는 것 같아요. 한번 최신 버전으로 업데이트 해볼래요?
> > 
> > 그리고 혹시 맥북이신가요?
> 
> 윈도우사용중입니다! gcc -v를 통해 확인한 결과 9.4.0 버전을 사용하고 있는데 11버전으로 업데이트 해보시란 말씀이 맞을까요?

이번 과제는 디버거가 필요없으니, 업데이트 하고도 설치가 안 된다면 넘어가고 과제부터 하는 게 좋을 것 같아요.

다음 스터디 수업 끝나고, 설치 안되시는 분들은 직접 봐드릴게요.
